config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'posts/index'
  root 'posts#index'

  resources :comments
  resources :posts
  resources :topics
  resources :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  belongs_to :post
  belongs_to :comment
  has_many :comment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :topic_id, :post_id, :content, :votes, :comment_id)
    end

    def authorize
      if current_user.nil?
        redirect_to login_url, alert: "Not authorized! Please log in."
      else
        if @comment && @comment.user != current_user
          redirect_to root_path, alert: "Not authorized! Only #{@comment.user} has access to this post."
        end
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- The user will be set by current_user after implementing authentication via Session  -->
  <!-- <div class="field">
    <%#= f.label :user_id %><br>
    <%#= f.text_field :user_id %>
  </div> -->

  <%# Don't show full name when the action calling the form partial is "new" %>
  <% if @comment.blank?%>
    <p>
      <strong>User: </strong>
      <%# Added full_name for display purposes originally would instead show the object hex such <User:0x...> when using @post.user%>
      <%full_name = @comment.user.first_name + " " + @comment.user.last_name %>
      <%= full_name %>
    </p>
  <% end %>

  <% if @comment.content.blank? #returns true, when it's a new comment%>
    <%# Then we set a hidden field to be saved as in the comments table ideontifying the author of this comment%>
    <%#= current_user%>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <% end %>

  <!-- Topic ID must be set by using the topic of the post which called the comment partial via "Reply" -->
  <%#= @post_topic_id = params[:topic_id] %>
  <%= f.hidden_field :topic_id, :value => params[:topic_id]%>
  <!-- <div class="field">
    <%#= f.label :topic_id %><br>
    <%#= f.text_field :topic_id %>
  </div> -->


  <!-- Post ID  must be set by the post that called the "new" action to create a comment via a "Reply to Post" button/link -->
  <%#= @post_id = params[:post_id] %>
  <%= f.hidden_field :post_id, :value => params[:post_id]%>
  <!-- <div class="field">
    <%#= f.label :post_id %><br>
    <%#= f.text_field :post_id %>
  </div> -->

  <div class="field">
    <%#= f.label :content %><br>
    <%= f.text_area :content, :size =>"60x10" %>
  </div>

  <!-- Votes must be implemented using a flag possibly checking if user has already voted (and perhaps checking against session cookie) -->
  <!-- <div class="field">
    <%#= f.label :votes %><br>
    <%#= f.number_field :votes %>
  </div> -->

  <!-- comment ID will be set by replying on comments (not the one on a post) this
  will serve as a way to group and identify replies to the same comment -->
  <!-- <strong><%#= params[:comment_id] %></strong> -->
  <%= f.hidden_field :comment_id, :value => params[:comment_id]%>

  <!-- <div class="field">
    <%#= f.label :comment_id %><br>
    <%#= f.text_field :comment_id %>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<table border="0" width="100%">
  <tr>
    <td style="width:33%;">&nbsp;<td>

    <td style="width:34%;">
      <div style="text-align:left;margin-left:2%; line-height:2em;color:#2095C9">
        <h1>Editing Comments</h1>
      </div>
      <%= render 'form' %>
      <%= link_to 'Show', @comment %> |
      <%= link_to 'Back to Posts', posts_path %>
    </td>

    <td style="width:33%;">&nbsp;</td>
  </tr>
</table>

app/views/comments/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
<div style="text-align:left;margin-left:2%; line-height:2em;color:#2095C9">
  <h1>Listing Comments</h1>
</div>


<table id="index-list" border="0" style="border-collapse:collapse;background-color:#eee; ">
  <thead>
    <tr>
      <th>User</th>
      <th>Topic</th>
      <th>Comment on Post</th>
      <th>Content</th>
      <th>Votes</th>
      <th>Parent comment id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr style="background-color:#eee; border:1px dotted #aaa;">
        <td style="width:8%"><%= @posted_by = "#{User.find(comment.user_id).first_name} #{User.find(comment.user_id).last_name}"%></td><%# comment.user %>
        <td style="width:8%"><%= @topic_title = Topic.find(comment.topic_id).title %></td> <%# replaced comment.topic %>
        <td style="width:12%"><%= @post_excerpt = truncate(Post.find(comment.post_id).content, :length =>15) %></td><%#replaced comment.post %>
        <td style="width:42%"><%= comment.content %></td>
        <td  style="width:5%"><%= comment.votes %></td>
        <% if comment.comment_id.nil? %>
          <td>Comment on post id: <%= Post.find(comment.post_id).id %></td>
        <%else%>
          <td  style="width:15%">Comment on comment id:<%= comment.comment_id %></td>
        <% end %>
        <td  style="width:5%"><%= link_to 'Show', comment %></td>
        <%# show the Edit link only on the comments that the currently logged in user can edit (per our authorize method for editing comments)%>
        <% if current_user && comment.user == current_user %>
          <td  style="width:5%"><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <%else%>
          <td  style="width:5%">&nbsp;</td>
        <%end%>

        <%# Much like posts the Destroy action has been removed for the time being
        as it would require to add a dependent attribute to delete all comments
        dependent on other comments (if implementing comments of comments)%>
        <%# show the Destroy link only on the post that the currently logged in user as we did for the eidot link above%>
        <%# if current_user && post.user == current_user %>
        <!-- <td><%#= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        <%#end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%# if current_user %>
  <%#= link_to 'New Comment', new_comment_path %>
<%# end %>

app/views/comments/new.html.erb
<table border="0" width="100%">
  <tr>
    <td style="width:30%;">&nbsp;<td>

    <td style="width:40%;">
      <div style="text-align:left;margin-left:2%; line-height:2em;color:#2095C9">
        <h1>New Comment</h1>
      </div>
      <%= render 'form' %>
      <%= link_to 'Cancel', posts_path %>
    </td>

  <td style="width:30%;">&nbsp;</td>
</tr>
</table>

app/views/comments/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
<table border="0" width="100%" style="margin-top:2%;">
  <tr>
    <td style="width:33%;">&nbsp;<td>

    <td style="width:34%;">
      <p>
        <strong>User:</strong>
        <%= @posted_by = "#{User.find(@comment.user_id).first_name} #{User.find(@comment.user_id).last_name}"%>
        <%#= @comment.user %>
      </p>

      <p>
        <strong>Under Topic:</strong>
        <%= @topic_title = Topic.find(@comment.topic_id).title %>
        <%#= @comment.topic %>
      </p>

      <p>
        <strong>Replied on Post:</strong>
        <%#= @comment.post %>
        <%= @post_excerpt = truncate(Post.find(@comment.post_id).content, length:33) %>
      </p>

      <p>
        <strong>Saying:</strong>
        <%= @comment.content %>
      </p>

      <p>
        <strong>Comment Received Votes:</strong>
        <%= @comment.votes %>
      </p>

      <p>
        <strong>Comment: </strong> This is a comment in
        <%if @comment.comment_id.nil? %>
          <%=" reply to a post."%>
        <%else%>
          <%=" reply to a comment."%>
        <%end%>
      </p>
      <%if current_user %>
      <%= link_to 'Edit', edit_comment_path(@comment) %> |
      <%end%>
      <%= link_to 'Back', posts_path %>
    </td>

    <td style="width:33%;">&nbsp;</td>
  </tr>
</table>