config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'posts/index'
  root 'posts#index'

  resources :comments
  resources :posts
  resources :topics
  resources :users

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :post
  has_many :comment
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :user_id, :archived, :votes)
    end

    def authorize
      if current_user.nil?
        redirect_to login_url, alert: "Not authorized! Please log in."
      end
    end
    
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <%# conditional will show full name when the action calling the form is "new" (or will get error since id would be nil)%>
  <% if @topic.id.present? %>
  <%#binding.pry%>
  <div class="field">
    <% @user_full_name = "#{User.find(@topic.user_id).first_name} #{User.find(@topic.user_id).last_name}"%>
    <strong>User: </strong><%= @user_full_name%>
  </div>
  <%end%>


  <% if @topic.title.blank? #returns true, when it's a new topic%>
    <%# Then we set a hidden field to be saved as in the comments table ideontifying the author of this comment%>
    <%#= current_user%>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <% end %>
  <%# User will be set by the current_user (implemented at ApplicationController level as a helper)
  left commented out here at the moment for dev/test to create test entry manually if needed %>
  <!-- <div class="field">
    <%#= f.label :user_id %><br>
    <%#= f.text_field :user_id %>
  </div> -->

  <!-- Archived should be accessible only to admins. Admin feature to implement once everything else is working  -->
  <!-- <div class="field">
    <%#= f.label :archived %><br>
    <%#= f.check_box :archived %>
  </div> -->


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<table border="0" width="100%">
  <tr>
    <td style="width:40%;">&nbsp;<td>
    <td style="width:20%;">
      <div style="text-align:left;margin-left:2%; line-height:2em;color:#2095C9">
        <h1>Editing Topic</h1>
      </div>
      <%= render 'form' %>
      <%= link_to 'Show', @topic %> |
      <%= link_to 'Back', topics_path %>
    </td>

  <td style="width:40%;">&nbsp;</td>
</tr>
</table>

app/views/topics/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
<table border="0" width="100%">
  <tr>
    <td style="width:33%;">&nbsp;<td>

    <td style="width:34%;">
      <div style="text-align:left;margin-left:2%; line-height:2em;color:#2095C9">
        <h1>Listing Topics</h1>
      </div>

      <table id="index-list">
        <thead>
          <tr>
            <th>Title</th>
            <th>User</th>
            <th>Archived</th>
            <th>Votes</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @topics.each do |topic| %>
            <tr>
              <td><%= topic.title %>&nbsp;</td>

              <td><%= @user_full_name = "#{User.find(topic.user_id).first_name} #{User.find(topic.user_id).last_name}"%><%#changed from .user to .user_id, then set to show full_name%></td>
              <td><%= topic.archived %></td>
              <td><%= topic.votes %></td>
              <td><%= link_to 'Show', topic %></td>
              <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
              <td><%#= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

    <%= link_to 'New Topic', new_topic_path %>&nbsp;|&nbsp;<%= link_to 'Back to Posts', posts_path %>
    </td>

    <td style="width:33%;">&nbsp;</td>
  </tr>
</table>

app/views/topics/new.html.erb
<table border="0" width="100%">
  <tr>
    <td style="width:41%;">&nbsp;<td>

    <td style="width:18%;">
      <h1>New Topic</h1>
      <%= render 'form' %>
      <%= link_to 'Topics List', topics_path %>&nbsp;|&nbsp;<%= link_to 'Back to Posts', posts_path %>
    </td>

    <td style="width:41%;">&nbsp;</td>
  </tr>
</table>

app/views/topics/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
<table border="0" width="100%" style="margin-top:2%;">
  <tr>
    <td style="width:41%;">&nbsp;<td>

    <td style="width:18%;">
      <p>
        <strong>Title:</strong>
        <%= @topic.title %>
      </p>

      <p>
        <strong>User:</strong>
        <%# Added full_name for display purposes originally would instead show the object hex such <User:0x...> when using @topic.user %>
        <%full_name = @topic.user.first_name + " " + @topic.user.last_name %>
        <%= full_name %>
      </p>

      <p>
        <strong>Archived:</strong>
        <%= @topic.archived %>
      </p>

      <p>
        <strong>Votes:</strong>
        <%= @topic.votes %>
      </p>

      <%= link_to 'Edit', edit_topic_path(@topic) %> |
      <%= link_to 'Back', topics_path %>
    </td>

    <td style="width:41%;">&nbsp;</td>
    </tr>
    </table>