config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'posts/index'
  root 'posts#index'

  resources :comments
  resources :posts
  resources :topics
  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :comment

  validates :content, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]



  # GET /posts
  # GET /posts.json
  def index
    # we sort posts alphabetically in Ascending order by topic (thanks Jaden for the joins guidance/code!)
    # also sorting by creation date in Descending order.
    @topics = Topic.all
    @comments = Comment.all
    @posts = Post.all.joins(:topic).order("topics.title ASC").order("created_at DESC")
    #@topic_by_title = Topic.order(title: :asc)
    #@posts = Post.all.order("#{@topic_by_title} ASC").order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @topics = Topic.all
  end

  # GET /posts/new
  def new
    @topics = Topic.all
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    #@post = Post.new(post_params)
    #changed code so that when user is logged in, the post is connected to current_user
    @post = current_user.posts.build(post_params)
    # binding.pry
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:topic_id, :content, :votes) #removed :user_id param since we're using current_user and won't need it as a post param
    end

    def authorize
      if current_user.nil?
        redirect_to login_url, alert: "Not authorized! Please log in."
      else
        if @post && @post.user != current_user
          redirect_to root_path, alert: "Not authorized! Only #{@post.user} has access to this post."
        end
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# Don't showing full name when the action calling the form partial is "new" %>
  <% if @post.blank?%>
    <p>
      <strong>User: </strong>
      <%# Added full_name for display purposes originally would instead show the object hex such <User:0x...> when using @post.user%>
      <%full_name = @post.user.first_name + " " + @post.user.last_name %>
      <%= full_name %>
    </p>
  <% end %>

  <%# Note: At this time once a post has been associated with a topic upon creation (new)
  we can't allow modifying it. For that to happen we would need to also propagate the
  changes to update all the comments and comments of comments that shared the same topic id %>

  <%# We display the dropdown with all available topics when creating a new post %>
  <%if (@topic.present?) || @post.content.nil? %>
    <div class="field">
      <%= f.label :topic_id %><br>
      <%#@topics = Topic.all %>
      <%= select_tag "post[topic_id]", options_from_collection_for_select(@topics, "id", "title") %>
    </div>
  <% elsif @post.nil? %>
  <%# We also skip displaying topic when the action calling the form partial is "new" and if the form
  is not called from the "new" action, then we show the post's topic, but we don't allow editing %>
    <div>
      <%# !!! Remember to move this to the controller !!! %>
      <p><%= @post_topic = Topic.find(params[:id]).title %></p>
    </div>
    <%end%>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :size => "60x6"%>
  </div>

  <%# Votes editing capability should be only available to admins it at all %>
  <!-- <div class="field">
    <%#= f.label :votes %><br>
    <%#= f.number_field :votes %>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<table border="0" width="100%">
  <tr>
    <td style="width:30%;">&nbsp;<td>
    <td style="width:40%;">
      <div style="text-align:left;margin-left:2%; line-height:2em;color:#2095C9">
          <h1>Editing Post</h1>
      </div>
      <%= render 'form' %>
      <%= link_to 'Show', @post %> |
      <%= link_to 'Back', posts_path %>
    </td>

    <td style="width:30%;">&nbsp;</td>
  </tr>
</table>

app/views/posts/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
<% if current_user %>
    <div style="text-align:left;margin-left:2%; line-height:2em;color:#2095C9"><%= link_to 'New Post', new_post_path %>&nbsp;|&nbsp;<%= link_to 'New Topic', new_topic_path %></div>
<% end %>

<div id="forum-view" >
<table style="text-align:center; border-collapse:collapse;">

    <% @posts.each do |post| %>
    <% @topic_title = Topic.find(post.topic_id).title%>
    <% @user_full_name = "#{User.find(post.user_id).first_name} #{User.find(post.user_id).last_name}" %>
      <tr style="background-color:#eee; border:1px dotted #aaa;" >
        <td class="user-full-name" style="width:5%; text-align:center;"><%= @user_full_name %></td> <%# changed to user_id from .user as it was showing the object value <0x0....>, later modified ot show the user's full name %>
        <td style="width:5%;"><%= @topic_title %></td> <%# changed to topic_id from .topic as it was showing the object value <0x0....>, later modified to show the topic's title %>
        <td style="width:50%; text-align:left;">
          <p class="post content"><%= post.content %></p>

          <%# show the Edit link only on the post that the currently logged in user can edit (per our authorize method for editing posts)%>
          <% if current_user && post.user == current_user %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%end%>

          <%# we pass the topic id of the post when calling the new action to create a new comment %>
          <p>
            <%= link_to 'Reply to Post', new_comment_path(:topic_id => post.topic_id, :post_id => post.id) %>
          </p>

          <%# Voting %>

          <table class="comments">
            <%@comments.each do |comment|%>

              <% if post.id == comment.post_id && comment.comment_id.nil?%>
              <tr>
                <td>
                  <%= comment.content %>
                  <p>
                    <%= link_to 'Reply to Comment', new_comment_path(:topic_id => post.topic_id, :post_id => post.id, :comment_id => comment.id) %>
                  </p>
                </td>
              </tr>
              <%end%>


              <% if post.id == comment.post_id && comment.comment_id.present?%>
              <tr>
                <td>
                  <%= comment.content %>
                  <p>
                    <%= link_to 'Reply to Comment', new_comment_path(:topic_id => post.topic_id, :post_id => post.id, :comment_id => comment.id) %>
                  </p>
                </td>
              </tr>
              <%end%>


            <% end %>
          </table>

        </td>

        <td style="width:5%;"></td>
      </tr>
    <% end %>

  </table>

  <br>
  <%# Show the link to Create a new post only when the user is logged in %>
  <div style="text-align:right;margin-right:2%;">
    <% if current_user %>
      <%= link_to 'New Post', new_post_path %>
    <% end %>
  </div>

</div>

app/views/posts/new.html.erb
<table border="0" width="100%">
  <tr>
    <td style="width:30%;">&nbsp;<td>
    <td style="width:40%;">
      <div style="text-align:left;margin-left:2%; line-height:2em;color:#2095C9">
        <h1>New Post</h1>
      </div>
      <%= render 'form' %>
      <%= link_to 'Back', posts_path %>
    </td>
    <td style="width:30%;">&nbsp;</td>
  </tr>
</table>

app/views/posts/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
<table border="0" width="100%">
  <tr>
    <td style="width:30%;">&nbsp;<td>
    <td style="width:40%;">
<p>
  <strong>User:</strong>
  <%# Added full_name for display purposes originally would instead show the object hex such <User:0x...> when using @post.user%>
  <%full_name = @post.user.first_name + " " + @post.user.last_name %>
  <%= full_name %>
</p>

<p>
  <strong>Topic:</strong>
  <%@topic = Topic.find(@post.topic_id)%>
  <%= @topic.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @post.votes %>
</p>

<%# show edit link only if the page is being viewed by a logged in user %>
<%if current_user%>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<%end%>
<%= link_to 'Back', posts_path %>
</td>

    <td style="width:41%;">&nbsp;</td>
  </tr>
</table>