config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'posts/index'
  root 'posts#index'

  resources :comments
  resources :posts
  resources :topics
  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microforum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <link href='https://fonts.googleapis.com/css?family=Tulpen+One' rel='stylesheet' type='text/css'>

  <!-- bootstrap -->
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <span style="margin-left: 2%; font-family: 'Tulpen One', cursive; font-size:2.1em;line-height:1.2em ">
      Microforum
    </span>
    &nbsp;&nbsp;
    <%= link_to 'Home', root_path %>|
    <% if current_user %>
      <!-- <%#= link_to 'Posts', posts_path %> | -->
      <%= link_to 'Topics', topics_path %>&nbsp;|&nbsp;<%= link_to "Log Out", logout_path %>
      Logged in as:  <%= current_user.email %>
    <% else %>
      <%= link_to "Sign Up", signup_path %>&nbsp;|&nbsp;<%= link_to "Log In", login_path %>
    <% end %>
  </nav>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, class: "alert alert-#{key}") do %>
      <div class="alert-message-container"><div class="alert-message"><%= value %></div>
    <% end %>
  <% end %>

<%= yield %>

</body>
</html>